# Generated by Django 5.0.3 on 2024-03-28 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_item_location_provider_type_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='The agents that do the job in the event', null=True, to=settings.AUTH_USER_MODEL, verbose_name='agents'),
        ),
    ]
