# Generated by Django 5.0.3 on 2024-03-30 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='confirm_date',
            field=models.DateField(blank=True, help_text='If values represent the date the contact confirmed the event', null=True, verbose_name='confirm date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='event_date',
            field=models.DateField(blank=True, help_text='The date of the event the contact want to do', null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_contact',
            field=models.DateField(auto_now_add=True, help_text='The date the contact contacted for the first time', verbose_name='first contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='agents',
            field=models.ManyToManyField(help_text='The agents that do the job in the event', to=settings.AUTH_USER_MODEL, verbose_name='agents'),
        ),
    ]
