# Generated by Django 5.0.3 on 2024-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contact_confirm_date_alter_contact_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of the contact', max_length=10, null=True, verbose_name='phone'),
        ),
    ]
