# Generated by Django 5.0.3 on 2024-03-30 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_contact',
            field=models.DateField(default=datetime.datetime.now, help_text='The date the contact contacted for the first time', verbose_name='first contact'),
        ),
    ]
