# Generated by Django 5.0.3 on 2024-03-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contact_first_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expensecategory', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vat number'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the event type', max_length=100, null=True, verbose_name='description'),
        ),
    ]
