# Generated by Django 5.0.3 on 2024-03-30 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expensecategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.now, help_text='The date of the event', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Create the end time initially but return to edit after the event to track the real job', verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Create the start time initially but return to edit after the event to track the real job', verbose_name='start time'),
        ),
    ]
