# Generated by Django 5.0.3 on 2024-03-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='busker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
    ]
