# Generated by Django 5.0.3 on 2024-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_busker_event_busker_currency_event_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Not required. The photo will be stored in the system', null=True, upload_to='item_images', verbose_name='image'),
        ),
    ]
