# Generated by Django 5.0.3 on 2024-04-05 20:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 7, 1, 20, 978749), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='On what day and at what time the event starts', verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(help_text='The name of the person who contacted', max_length=100, unique=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of the contact', max_length=10, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='latidude of the location', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='longitude of the location', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(help_text='The phone number of the provider', max_length=10, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='vat number'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='The name of the type', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('first_name', 'last_name')},
        ),
    ]
