# Generated by Django 5.0.3 on 2024-04-05 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_event_date_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 5, 5, 20, 742860, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 20, 5, 20, 742860, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event starts', verbose_name='start time'),
        ),
    ]
