# Generated by Django 5.0.3 on 2024-04-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_setting_options_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 20, 27, 47, 434650, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the setting', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(help_text='The name of the setting', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(help_text='The value of the setting. This value is stored as a string for compliance purpose', max_length=500, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('b', 'boolean'), ('f', 'float')], default='s', help_text='The description of the setting', max_length=1, verbose_name='description'),
        ),
    ]
