# Generated by Django 5.0.3 on 2024-04-12 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_event_end_date_alter_setting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, choices=[('AG', 'Agrigento'), ('AL', 'Alessandria'), ('AN', 'Ancona'), ('AO', 'Aosta'), ('AP', 'Ascoli-Piceno'), ('AQ', 'L’Aquila'), ('AR', 'Arezzo'), ('AT', 'Asti'), ('AV', 'Avellino'), ('BA', 'Bari'), ('BG', 'Bergamo'), ('BI', 'Biella'), ('BL', 'Belluno'), ('BN', 'Benevento'), ('BO', 'Bologna'), ('BR', 'Brindisi'), ('BS', 'Brescia'), ('BT', 'Barletta-Andria-Trani'), ('BZ', 'Bolzano'), ('CA', 'Cagliari'), ('CB', 'Campobasso'), ('CE', 'Caserta'), ('CH', 'Chieti'), ('CI', 'Carbonia Iglesias'), ('CL', 'Caltanissetta'), ('CN', 'Cuneo'), ('CO', 'Como'), ('CR', 'Cremona'), ('CS', 'Cosenza'), ('CT', 'Catania'), ('CZ', 'Catanzaro'), ('EN', 'Enna'), ('FC', 'Forli-Cesena'), ('FE', 'Ferrara'), ('FG', 'Foggia'), ('FI', 'Firenze'), ('FM', 'Fermo'), ('FR', 'Frosinone'), ('GE', 'Genova'), ('GO', 'Gorizia'), ('GR', 'Grosseto'), ('IM', 'Imperia'), ('IS', 'Isernia'), ('KR', 'Crotone'), ('LC', 'Lecco'), ('LE', 'Lecce'), ('LI', 'Livorno'), ('LO', 'Lodi'), ('LT', 'Latina'), ('LU', 'Lucca'), ('MB', 'Monza-Brianza'), ('MC', 'Macerata'), ('ME', 'Messina'), ('MI', 'Milano'), ('MN', 'Mantova'), ('MO', 'Modena'), ('MS', 'Massa-Carrara'), ('MT', 'Matera'), ('NA', 'Napoli'), ('NO', 'Novara'), ('NU', 'Nuoro'), ('OG', 'Ogliastra'), ('OR', 'Oristano'), ('OT', 'Olbia Tempio'), ('PA', 'Palermo'), ('PC', 'Piacenza'), ('PD', 'Padova'), ('PE', 'Pescara'), ('PG', 'Perugia'), ('PI', 'Pisa'), ('PN', 'Pordenone'), ('PO', 'Prato'), ('PR', 'Parma'), ('PT', 'Pistoia'), ('PU', 'Pesaro-Urbino'), ('PV', 'Pavia'), ('PZ', 'Potenza'), ('RA', 'Ravenna'), ('RC', 'Reggio-Calabria'), ('RE', 'Reggio-Emilia'), ('RG', 'Ragusa'), ('RI', 'Rieti'), ('RN', 'Rimini'), ('RO', 'Rovigo'), ('Roma', 'Roma'), ('SA', 'Salerno'), ('SI', 'Siena'), ('SO', 'Sondrio'), ('SP', 'La-Spezia'), ('SR', 'Siracusa'), ('SS', 'Sassari'), ('SV', 'Savona'), ('TA', 'Taranto'), ('TE', 'Teramo'), ('TN', 'Trento'), ('TO', 'Torino'), ('TP', 'Trapani'), ('TR', 'Terni'), ('TS', 'Trieste'), ('TV', 'Treviso'), ('UD', 'Udine'), ('VA', 'Varese'), ('VB', 'Verbania'), ('VC', 'Vercelli'), ('VE', 'Venezia'), ('VI', 'Vicenza'), ('VR', 'Verona'), ('VS', 'Medio Campidano'), ('VT', 'Viterbo'), ('VV', 'Vibo-Valentia')], default='BA', help_text='The province of the city', max_length=4, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 22, 30, 26, 396826, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('b', 'boolean'), ('f', 'float')], default='s', help_text='The type of the setting', max_length=1, verbose_name='Type'),
        ),
    ]
