# Generated by Django 5.0.3 on 2024-04-13 13:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_location_province_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='From which day it starts to be valid', verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 33, 32, 63731, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
    ]
