# Generated by Django 5.0.3 on 2024-04-19 17:10

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_setting_valid_from_alter_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cancel_date',
            field=models.DateField(blank=True, help_text='If valued indicate that the event was canceled. In the additional info should be written why', null=True, verbose_name='cancel date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='confirm_date',
            field=models.DateField(blank=True, help_text='If valued represent the date the contact confirmed the event', null=True, verbose_name='confirm date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 19, 10, 2, 616641, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date of the expense', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
