# Generated by Django 5.0.3 on 2024-04-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_contact_cancel_date_alter_contact_confirm_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 9, 53, 13, 766926, tzinfo=datetime.timezone.utc), help_text='On what day and at what time the event ends', verbose_name='end time'),
        ),
    ]
